// <auto-generated />
namespace CMD.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addUltimaModificaçãoMedidas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUltimaModificaçãoMedidas));
        
        string IMigrationMetadata.Id
        {
            get { return "201803011941362_addUltimaModificaçãoMedidas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
